CREATE TABLE ADDRESS_USER
( id INT  AUTO_INCREMENT PRIMARY KEY ,
logradouro VARCHAR (100) NOT NULL ,
numero INT NOT NULL ,
complemento VARCHAR (50) ,
bairro VARCHAR (50)NOT NULL ,
cidade VARCHAR (50)NOT NULL ,
estado  VARCHAR (50)NOT NULL) ;